using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;


public class DeadthCreen : MonoBehaviour
{
  
    // Start is called before the first frame update
    void Start()
    {
        gameObject.SetActive(false);
    }

    // Update is called once per frame
/*    void Update()
    {
        if (Player.isDead==true)
        {
            gameObject.SetActive(true);
            Time.timeScale = 0f;
        }
    }*/

    public void ToggleEndMenu()
    {

        gameObject.SetActive(true);
        Time.timeScale = 0f;
        

    }
    
}
